"""
This file is automatically generated by autosetup.py
Please edit the marked area only. Other areas will be
overwritten when autosetup is reruns.
"""

from setuptools import setup

params = dict(
    name='aws2',
    description='{',
    version='0.2.1',
    url='https://github.com/simonm3/aws2.git',
    install_requires=['boto3', 'botocore', 'fabric',
                      'pandas', 'pyperclip', 'requests'],
    packages=['aws2'],
    data_files=[
        ('./etc/aws2', ['licence.txt', 'readme.ipynb', 'readme.md', 'version'])],
    py_modules=[],
    include_package_data=True,
    scripts=None)

########## EDIT BELOW THIS LINE ONLY ##########

# optional but useful
params["install_requires"].append("nbextensions")

########## EDIT ABOVE THIS LINE ONLY ##########

setup(**params)
