ImageId: ami-03d8261f577d71b6a
InstanceType: t3.nano
KeyName: key
SecurityGroups:
- default
MinCount: 1
MaxCount: 1
BlockDeviceMappings:
- DeviceName: /dev/sda1
  Ebs:
    DeleteOnTermination: false
    VolumeType: gp2